# Generated by Django 4.2.18 on 2025-01-24 11:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_page_translation_snipet_pagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('lft', models.IntegerField(default=0)),
                ('rght', models.IntegerField(default=0)),
                ('tree_id', models.IntegerField(default=0)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.menuitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.menuitem')),
            ],
            options={
                'unique_together': {('menuitem', 'lang')},
            },
        ),
    ]
