# Generated by Django 4.2.18 on 2025-01-25 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_menuitem_menutranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='test', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='URL может содержать только латинские буквы, цифры и дефис.', regex='^[a-zA-Z0-9-]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='URL может содержать только латинские буквы, цифры и дефис.', regex='^[a-zA-Z0-9-]+$')]),
        ),
    ]
