# Generated by Django 4.2.18 on 2025-01-25 10:59

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_url_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='URL может содержать только латинские буквы, цифры и дефис.', regex='^[a-zA-Z0-9-]+$')]),
        ),
    ]
