# Generated by Django 4.2.18 on 2025-01-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_page_content_page_title_post_content_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snipet',
            field=models.TextField(blank=True),
        ),
    ]
