# Generated by Django 4.2.18 on 2025-01-28 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_page_title_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='URL может содержать только латинские буквы, цифры и дефис.', regex='^[a-zA-Z0-9-]+$')])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('row', models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2'), (3, 'Row 3')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FooterMenuTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.footermenu')),
            ],
            options={
                'unique_together': {('item', 'lang')},
            },
        ),
    ]
