# Generated by Django 4.2.18 on 2025-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_footermenu_footermenutranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenu',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
