# Generated by Django 4.2.18 on 2025-01-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_footermenu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My site', max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, null=True, verbose_name='Описание сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='row',
            field=models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2')], default=1),
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=4)),
                ('site_name', models.CharField(max_length=200)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.sitesettings')),
            ],
            options={
                'unique_together': {('item', 'lang')},
            },
        ),
    ]
