# Generated by Django 4.2.18 on 2025-01-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_sitesettings_alter_footermenu_row_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo',
            new_name='image',
        ),
    ]
