# Generated by Django 4.2.18 on 2025-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_logo_sitesettings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_name',
            field=models.CharField(default='News', max_length=255, verbose_name='Название раздела с публикациями'),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='blog_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
