# Generated by Django 4.2.18 on 2025-01-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_social_socialtranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='icon',
            new_name='image',
        ),
    ]
