# Generated by Django 4.2.18 on 2025-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_contacts_contactstranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
