# Generated by Django 4.2.18 on 2025-02-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_pagetranslation_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='footermenu',
            options={'verbose_name': 'Footer menu', 'verbose_name_plural': 'Footer menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Main menu', 'verbose_name_plural': 'Main menu'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_name',
            field=models.CharField(default='News', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='image',
            field=models.ImageField(null=True, upload_to='site_logo/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='My site', max_length=255),
        ),
    ]
