# Generated by Django 4.2.19 on 2025-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_category_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon',
            field=models.ImageField(null=True, upload_to='site_logo/'),
        ),
    ]
