# Generated by Django 4.2.19 on 2025-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_sitesettings_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/'),
        ),
    ]
