# Generated by Django 4.2.19 on 2025-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_sitesettings_icon_alter_sitesettings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_url',
            field=models.CharField(default='news', max_length=32),
        ),
    ]
