# Generated by Django 4.2.19 on 2025-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_sitesettings_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_url',
            field=models.CharField(default='news', help_text='Changes to this setting will only take effect after the application is restarted.', max_length=32),
        ),
    ]
