# Generated by Django 4.2.19 on 2025-02-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_sitesettings_blog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cache',
                'verbose_name_plural': 'Cache',
            },
        ),
    ]
