# Generated by Django 4.2.19 on 2025-02-18 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_cachecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='URL can contain only Latin letters, numbers and hyphens.', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='sitesettingstranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='socialtranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='translation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
