# Generated by Django 4.2.19 on 2025-02-19 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_post_url_alter_sitesettingstranslation_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='URL can contain only Latin letters, numbers and hyphens.', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='contactstranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='footermenutranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='menutranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='URL can contain only Latin letters, numbers and hyphens.', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
