# Generated by Django 4.2.19 on 2025-02-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_category_url_alter_contactstranslation_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='lang',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
