# Generated by Django 4.2.19 on 2025-02-27 18:57

import blog.models.social
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_categorytranslation_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='val',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='row',
            field=models.IntegerField(choices=[(1, 'Row 1'), (2, 'Row 2')], default=1, verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snipet',
            field=models.TextField(blank=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_name',
            field=models.CharField(default='News', max_length=255, verbose_name='Title of the section with publications'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_url',
            field=models.CharField(default='news', help_text='Changes to this setting will only take effect after the application is restarted.', max_length=32, verbose_name='URL of the section with publications'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='Site icon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, null=True, verbose_name='Site description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='My site', max_length=255, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='social_icons/', validators=[blog.models.social.validate_svg], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
