# Generated by Django 4.2.19 on 2025-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_crypto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='donations',
            name='default_amount',
            field=models.IntegerField(default=10, verbose_name='Donation amount by default'),
        ),
        migrations.AddField(
            model_name='donations',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='donations',
            name='payment_name',
            field=models.CharField(default='Donation', max_length=255, verbose_name='Payment name'),
        ),
    ]
