# Generated by Django 4.2.19 on 2025-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donations_options_donations_default_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='name',
        ),
        migrations.AddField(
            model_name='donations',
            name='currency',
            field=models.CharField(default='usd', max_length=5, verbose_name='Currency'),
        ),
    ]
